export const SHARED = 'SHARED';
export const ADDED = 'ADDED';
export const CREATE_SHARED_START = 'CREATE_SHARED_START';
export const CREATE_SHARED_SUCCESS = 'CREATE_SHARED_SUCCESS';
export const CREATE_SHARED_FAIL = 'CREATE_SHARED_FAIL';
