export const ADD_CHOICE_START = 'ADD_CHOICE_START';
export const ADD_CHOICE_SUCCESS = 'ADD_CHOICE_SUCCESS';
export const ADD_CHOICE_FAIL = 'ADD_CHOICE_FAIL';

export const FETCH_SHARED_START = 'FETCH_SHARED_START';
export const FETCH_SHARED_SUCCESS = 'FETCH_SHARED_SUCCESS';
export const FETCH_SHARED_FAIL = 'FETCH_SHARED_FAIL';

export const CREATE_SHARED_START = 'CREATE_SHARED_START';
export const CREATE_SHARED_SUCCESS = 'CREATE_SHARED_SUCCESS';
export const CREATE_SHARED_FAIL = 'CREATE_SHARED_FAIL';
